AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Lambda
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-cc8efa6d-c69b-42ef-b493-9a6adf243943
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::411763187466:role/service-role/search-photos-role-j5arb6oj'
