AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Lambda
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-cc8efa6d-c69b-42ef-b493-9a6adf243943
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::411763187466:role/service-role/search-photos-role-j5arb6oj'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /search
            Method: OPTIONS
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api4:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api5:
          Type: Api
          Properties:
            Path: /search
            Method: GET
        Api6:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
